### ISSUE TITLE
Clarify error message or create pack root directory by default

### ISSUE THREAD

**Issue by mhkline** [Open-CMSIS-Pack/gen-pack#24]
Thanks for putting together this tool. I'm trying to learn about packs and how we can use them at our company.

While going through the tutorial, I got stuck with the following error while trying to run `gen_pack.sh`.

```
Error: Cannot find CMSIS_PACK_ROOT
Action: Set CMSIS_PACK_ROOT to point to your pack folder
```

By digging through the source, I eventually figured out that this was happening because the pack directory did not exist. I thought the problem was that the script could not find the CMSIS_PACK_ROOT environment variable.

Here's the line:

https://github.com/Open-CMSIS-Pack/gen-pack/blob/c8a5ef3a329606a9870941e53fa4e99244318e19/lib/utilities#L75

Anyway, I think it would be helpful to either change the error message to "Directory does not exist", or just create the directory by default. What do you think?

**Comment by jkrech** [comment]
I agree, that we should change the error message to something like:
`Error: Directory specified by CMSIS_PACK_ROOT environment variable does not exist`
I would not vote for extra "magic" but rather require people to use an initialized CMSIS_PACK_ROOT.
It is `cpackget init` command people should run for setting up a CMSIS Pack Repository.

**Comment by JonatanAntoni** [comment]
@mhkline, please review #25 if this gets clear from the messages, now.

**Comment by mhkline** [comment]
Done. Thank you for the clarification. This also taught me about cpackage init.
