### ISSUE TITLE
Patch file requires LF line ending

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/gen-pack#44]
Patch files can be specified in PACK_PATCH_FILES.
The line ending of patch files needs to be LF. Otherwise, patching fails. 

This might be a problem when a repository is checked out on Windows with autocrlf=true. User would need to be aware of this and ensure that patch files have the LF line ending (for example specifying it via .gitattributes). 

Maybe an alternative would be to run the patch command with --binary options (seems to accept also patch files with CRLF line ending).

**Comment by JonatanAntoni** [comment]
@RobertRostohar, PR #45 should fix this issue. Can you verify and comment on the PR, please?

**Comment by RobertRostohar** [comment]
PR #45 looks good.
