### ISSUE TITLE
gen_pack: command not found

### ISSUE THREAD

**Issue by DinoHaw** [Open-CMSIS-Pack/gen-pack#51]
Hi, I installed git, xmllint and 7-zip as per the information and steps given in the README, and copied the latest version of `gen_pack.sh` in the [template](https://github.com/Open-CMSIS-Pack/gen-pack/tree/main/template) folder to my working directory after executing the `git update-index --chmod=+x gen_pack.sh` command. 
I also modified `gen_pack.sh` [gen_pack.zip](https://github.com/Open-CMSIS-Pack/gen-pack/files/13603252/gen_pack.zip) as per the steps and executed command `./gen_pack.sh` in git bash, but it says `gen_pack: command not found`.
![image](https://github.com/Open-CMSIS-Pack/gen-pack/assets/43368876/425ceab9-0a47-4d8b-91e9-2bd1ac5ad857)

I thought it was because the `gen_pack.sh` script couldn't get the location of `gen_pack`, so I tried both methods of placing `gen-pack` in my working directory and adding the directory where `gen-pack` is located to the system environment variable `Path`, but neither of them worked, the second method ended after printing these messages in the image below  (in order to make it executable, I made an extra copy of `gen-pack` and renamed it to `gen_pack`). How can I solve this problem? Thank you for your help.
![image](https://github.com/Open-CMSIS-Pack/gen-pack/assets/43368876/661213fc-e666-43a3-9885-44452044316d)

**Comment by JonatanAntoni** [comment]
Hi @DinoHaw,

Looks like you are facing multiple issues.

Given you are using the `gen_pack.sh` template from here:
https://github.com/Open-CMSIS-Pack/gen-pack/blob/cebe15cebe986304d826d82577c9c1c7bf67e2c7/template/gen_pack.sh#L107-L111

You can see, there are two ways the gen-pack library can be loaded. The default way is in line 110 by sourcing the bootstrap script:
https://github.com/Open-CMSIS-Pack/gen-pack/blob/cebe15cebe986304d826d82577c9c1c7bf67e2c7/bootstrap#L35-L40

This bootstrap script downloads the required version of the library and sources it. The final  `gen_pack` call in `gen_pack.sh` refers to the main function of the library.

Alternatively, you can install any version of the gen-pack library, manually. For example, cloning the repository as you did in the second try. By setting `GEN_PACK_LIB_PATH` to point to the repository root (where the `gen-pack` entry point is) makes this library to be used.

In your case, this seems to be working. Now, you suffer from a incomplete bash environment. I.e., on your machine there is no `LANG` environment variable set. The gen-pack library relies on UTF-8 encoding (e.g., used for filenames). Any other encoding could cause weird behaviour. As a fallback, the library tries to detect the encoding itself and assumes `LANG=zh_CN.UTF-8`.

What looks strange is, that even when calling `gen_pack.sh -h` it does not print out the usage text as expected. Can you please run the script with trace? I.e., do `bash -x gen_pack.sh -h 2> trace.log` and attach the `trace.log` to your reply.
