### ISSUE TITLE
Should it prompt and automatically install `cmsis-toolbox` if it is not installed?

### ISSUE THREAD

**Issue by HalfSweet** [Open-CMSIS-Pack/gen-pack#53]
On computers that have not had a development environment installed, if you run the gen_pack.sh command directly, you will be prompted that the `PackChk` command is missing. However, it does not automatically resolve this dependency, and there is no hint that `cmsis-toolbox` needs to be installed, not even in the README's preconditions.Should it prompt and automatically install `cmsis-toolbox` if it is not installed?

**Comment by JonatanAntoni** [comment]
Hi @HalfSweet,

In general `gen_pack.sh` does not install tools automatically, except the required gen-pack library itself.

I admit just asking for PackChk without any hint where it can be found is somehow cryptic.
I am fine with enhancing the log output pointing the user to CMSIS-Toolbox.

And yes, the README is missing this dependency as well.
Would you like to contribute the enhancements in terms of a pull-request?
